apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-ms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-demo-ms
  template:
    metadata:
      labels:
        app: java-demo-ms
    spec:
      containers:
      - name: java-demo-ms
        image: charanjops/java-demo-ms:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: JAVA_OPTS
          value: "-Xmx128m -Xms128m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-ms
spec:
  selector:
    app: java-demo-ms
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer